[package]
name = "prism-js"
description = "rust bindings for prism.js syntax highlighting library"
edition = "2021"
license = "MIT"
readme = "readme.md"
repository = "https://github.com/FraserLee/prism-rs"
version = "0.1.0"

[dependencies]
quick-js = "0.4.1"
